/* Catalogue de démonstration — à remplacer par de vrais produits/liens affiliés */

const img = (seed, w = 600, h = 450) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

const CF_PRODUCTS = [
  {
    // lien affilié CWD à renseigner (CTA -> href="#" en attendant)
    id: 'selle-voltige-confort',
    name: 'La référence du CSO',
    category: 'selles',
    tag: 'Selle CSO',
    detailUrl: '/equipement/selles/cwd-se01/',
    equipementUrl: '/equipement/selles/cwd-se01/',
    subtitle: 'CWD SE01 — siège plat, close contact, cuir français',
    desc: "La selle incontournable des cavalières de CSO. Siège plat avec enfourchure fine pour un maximum de proximité avec le cheval, arçon bois nouvelle génération avec mousse à mémoire de forme. Un classique indétrônable.",
    price: 'À partir de 1 300€ d\'occasion',
    oldPrice: null,
    badge: 'coup-de-coeur',
    ctaLabel: 'Voir la selle',
    img: '/assets/selle-cwd.jpg',
    disciplines: ['cso'],
    morphology: [],
    budget: '3000+',
  },
  {
    id: 'selle-dressage-antares',
    name: 'La selle de dressage française par excellence',
    category: 'selles',
    tag: 'Selle Dressage',
    equipementUrl: '/equipement/selles/antares-dressage/',
    subtitle: 'Antarès Sellier — artisanat français, confort ultime',
    desc: "Maison française fondée à Saintes, sur-mesure, demi-mesure ou prêt-à-porter. Arçon en bois lamellé collé et panneaux anatomiques mono densité pour un confort et une performance optimale en dressage.",
    price: 'À partir de 2 000€ d\'occasion — Neuve dès 2 800€',
    oldPrice: null,
    badge: 'dressage',
    img: '/assets/selle-antares-dressage.jpg',
    disciplines: ['dressage'],
    morphology: [],
    budget: '1500-3000',
  },
  {
    id: 'selle-cso-dos-large',
    name: 'Selle CSO "Grand Dos"',
    category: 'selles',
    tag: 'Selle CSO',
    detailUrl: '/bons-plans/selle-cso-grand-dos/',
    desc: "Arçon large et quartiers évasés pour les chevaux ronds et puissants type Selle Français ou Cob.",
    price: '2350€',
    oldPrice: '2690€',
    badge: 'promo',
    img: img('selle3'),
    disciplines: ['cso'],
    morphology: ['dos-large'],
    budget: '1500-3000',
  },
  {
    id: 'selle-cso-devoucoux-biarritz',
    name: "La selle CSO qui s'adapte à tout",
    category: 'selles',
    tag: 'Selle CSO',
    equipementUrl: '/equipement/selles/devoucoux-biarritz/',
    subtitle: 'Devoucoux Biarritz — mixte obstacle, plat et extérieur',
    desc: "Fabrication artisanale française au Pays Basque, panneaux D3D en mousse injectée souple et siège semi-creux à équilibre central. Polyvalente : obstacle, plat et extérieur.",
    price: 'À partir de 1 000€ d\'occasion — Neuve à partir de 3 060€',
    oldPrice: null,
    badge: 'cso',
    img: '/assets/selle-devoucoux-biarritz.jpg',
    disciplines: ['cso'],
    morphology: [],
    budget: '500-1500',
  },
  {
    id: 'selle-kramer-tous-budgets',
    name: 'Une selle pour chaque budget',
    category: 'selles',
    tag: 'Selle',
    equipementUrl: '/equipement/selles/kramer-tous-budgets/',
    subtitle: 'Kramer Equitation — de l\'entrée de gamme au haut de gamme',
    desc: "Plus de 25 000 articles disponibles et trois gammes bien distinctes — Wintec, Showmaster et Claridge House — pour trouver la selle adaptée à ton budget et ton niveau.",
    price: 'À partir de 200€',
    oldPrice: null,
    badge: 'tous-budgets',
    img: '/assets/selle-kramer-tous-budgets.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'filet-anatomique-dyon',
    name: 'La référence haut de gamme',
    category: 'filets',
    tag: 'Filets & embouchures',
    subtitle: "Dy'on — filet anatomique artisanal belge",
    desc: "Conçu avec des cavaliers professionnels, découpe anatomique précise pour éviter tout point de pression sur la nuque et les oreilles. La référence absolue pour les chevaux sensibles.",
    price: 'Sur devis / revendeur agréé',
    oldPrice: null,
    badge: 'premium',
    ctas: [{ label: 'Voir chez Equi-Clic', href: 'https://equi-clic.com/fr/303-bride-cheval' }],
    img: img('filet-dyon'),
    disciplines: ['dressage', 'cso', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'filet-anatomique-horze',
    name: 'Le meilleur rapport qualité/prix',
    category: 'filets',
    tag: 'Filets & embouchures',
    subtitle: 'Horze — filet anatomique Clermont',
    desc: "Dégage bien les oreilles, cuir souple dès le premier jour, idéal pour les chevaux à peau sensible. Le bon plan pour un usage quotidien sans compromis sur le confort.",
    price: 'Dès 49€',
    oldPrice: null,
    badge: 'promo',
    ctas: [{ label: 'Voir sur Horze', href: 'https://horze.fr/brides-anatomiques' }],
    img: img('filet-horze'),
    disciplines: ['dressage', 'cso', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'filet-anatomique-hkm',
    name: 'Le best-seller accessible',
    category: 'filets',
    tag: 'Filets & embouchures',
    subtitle: 'HKM Anatomic Crystal',
    desc: "Best-seller reconnu, existe en version cristaux pour les concours. Solide, confortable et esthétique. Parfait pour débuter avec un filet anatomique sans se ruiner.",
    price: 'Dès 39€',
    oldPrice: null,
    badge: 'best-seller',
    ctas: [{ label: 'Voir sur Equi-Clic', href: 'https://equi-clic.com/fr/200-filet-et-bridon-cheval' }],
    img: img('filet-hkm'),
    disciplines: ['dressage', 'cso', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'mors-simple-chantilly',
    name: 'Le mors de toutes les bouches',
    category: 'filets',
    tag: 'Embouchure',
    equipementUrl: '/equipement/filets-embouchures/mors-chantilly/',
    subtitle: 'Mors simple Chantilly — douceur et légèreté',
    desc: "Le mors le plus doux et le plus léger du marché — anneaux ronds coulissants, action directe et sans levier. Parfait pour débuter ou pour les bouches sensibles.",
    price: 'Dès 15€',
    oldPrice: null,
    badge: null,
    img: '/assets/mors-chantilly.jpg',
    disciplines: ['loisir', 'dressage', 'cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'mors-double-brise-doux',
    name: 'Le mors qui met tout le monde d\'accord',
    category: 'filets',
    tag: 'Embouchure',
    equipementUrl: '/equipement/filets-embouchures/mors-double-brisure/',
    subtitle: 'Mors double brisure en caoutchouc — douceur maximale',
    desc: "Caoutchouc souple et flexible, le matériau le plus doux qui soit pour la bouche du cheval. Double brisure qui répartit uniformément la pression, idéal pour les jeunes chevaux ou les bouches sensibles.",
    price: 'Dès 20€',
    oldPrice: null,
    badge: null,
    img: '/assets/mors-double-brisure.jpg',
    disciplines: ['loisir', 'dressage'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'mors-baucher',
    name: "Le mors releveur pour un cheval plus léger",
    category: 'filets',
    tag: 'Embouchure',
    equipementUrl: '/equipement/filets-embouchures/mors-baucher/',
    subtitle: 'Mors Baucher — précision, cession de nuque et placer',
    desc: "Double effet releveur et abaisseur pour un basculement de nuque et un meilleur placer du cheval. Un mors précis, réservé aux cavalières confirmées maîtrisant l'indépendance de leurs mains.",
    price: 'Dès 30€',
    oldPrice: null,
    badge: null,
    img: '/assets/mors-baucher.jpg',
    disciplines: ['dressage', 'cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'mors-pessoa',
    name: 'Le mors réglable qui redresse et allège',
    category: 'filets',
    tag: 'Embouchure',
    equipementUrl: '/equipement/filets-embouchures/mors-pessoa/',
    subtitle: 'Mors Pessoa — releveur, réglable, sans gourmette',
    desc: "Mors réglable qui permet de doser précisément la puissance selon l'anneau utilisé, sans gourmette. Double action : levier dans la bouche et pression sur la nuque simultanément.",
    price: 'Dès 30€',
    oldPrice: null,
    badge: null,
    img: '/assets/mors-pessoa.jpg',
    disciplines: ['cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'filet-horze-clermont-marron',
    name: "L'élégance naturelle du cuir marron",
    category: 'filets',
    tag: 'Bride',
    equipementUrl: '/equipement/filets-embouchures/filet-clermont-marron/',
    subtitle: 'Horze Clermont — filet anatomique cuir marron foncé',
    desc: "Cuir véritable souple et résistant, têtière et muserolle anatomiques matelassées, frontal orné d'une chaînette de cristaux en V. Qualité premium à un prix accessible.",
    price: 'Dès 89€',
    oldPrice: null,
    badge: null,
    img: '/assets/filet-clermont-marron.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'filet-horze-clermont-noir',
    name: 'Le classique indétrônable du concours',
    category: 'filets',
    tag: 'Bride',
    equipementUrl: '/equipement/filets-embouchures/filet-clermont-noir/',
    subtitle: 'Horze Clermont — filet anatomique cuir noir',
    desc: "Cuir véritable noir, le grand classique du concours. Têtière et muserolle anatomiques matelassées, frontal orné d'une chaînette de cristaux en V. Sobre et élégant en toutes circonstances.",
    price: 'Dès 89€',
    oldPrice: null,
    badge: null,
    img: '/assets/filet-clermont-noir.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'tapis-harcour-versailles',
    name: 'Collection limitée Harcour x Versailles',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    pepiteUrl: '/pepites/tapis-harcour-versailles/',
    equipementUrl: '/pepites/tapis-harcour-versailles/',
    subtitle: 'Harcour x Versailles — Collection Charles Marine',
    desc: "Collection exclusive Harcour x Versailles, coupe anatomique dégarrottée et intérieur en coton gaufré. Un tapis collector élégant qui reste bien en place même dans les séances les plus intenses.",
    price: '69,98€',
    oldPrice: null,
    badge: 'promo',
    img: '/assets/tapis-harcour-versailles.jpg',
    disciplines: [],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'guetres-veredus-carbon-gel',
    name: 'Guêtres de protection CSO',
    category: 'protections',
    tag: 'Protections & tendons',
    pepiteUrl: '/pepites/guetres-veredus-carbon-gel/',
    equipementUrl: '/equipement/protection/guetres-veredus-carbon-gel/',
    subtitle: 'Veredus Carbon Gel Vento — guêtres antérieures brown',
    desc: "Premières guêtres au monde à double ventilation, coque anatomique en carbone et Nitrexgel intégré. Testées et approuvées par Marcus Ehning et les plus grands cavaliers internationaux de CSO.",
    price: '209,99€',
    oldPrice: null,
    badge: 'promo',
    img: '/assets/guetres-veredus-carbon-gel.jpg',
    disciplines: ['cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'guetres-horze-supreme',
    name: 'La protection quotidienne sans se ruiner',
    category: 'protections',
    tag: 'Protections & tendons',
    equipementUrl: '/equipement/protection/guetres-horze-supreme/',
    subtitle: 'Horze Supreme — guêtres légères et respirantes',
    desc: "Néoprène respirant sur toute la surface, coque de protection anatomique et fermeture velcro double solide. Disponibles en plusieurs coloris, lavables en machine. Le bon plan protection au quotidien.",
    price: 'Dès 29,99€',
    oldPrice: null,
    badge: null,
    img: '/assets/guetres-horze-supreme.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'protections-boulets-cso',
    name: 'Protège-boulets ajourés compétition',
    category: 'protections',
    tag: 'Protections & boulets',
    detailUrl: '/bons-plans/protege-boulets-ajoures/',
    desc: "Ventilation maximale et fermeture rapide, plébiscités en concours de saut d'obstacles.",
    price: '65€',
    oldPrice: '85€',
    badge: 'promo',
    img: img('boulet1'),
    disciplines: ['cso'],
    morphology: [],
    budget: '<500',
  },
  {
    // lien affilié Decathlon à renseigner (CTA -> href="#" en attendant)
    id: 'masque-mouches-fouganza',
    name: "Le bon plan de l'été",
    category: 'protections',
    tag: 'Protection',
    detailUrl: '/equipement/protection/masque-anti-mouches/',
    subtitle: 'Masque anti-mouches Fouganza 500 — Decathlon',
    desc: "Le masque anti-mouches incontournable à petit prix. Grille semi-rigide qui évite tout contact avec les yeux, mesh respirant et résistant, fermeture velcro. Protège les oreilles, les yeux et le nez. Compatible avec les chemises anti-mouches Fouganza. Noté 4.3/5 sur plus de 1 700 avis.",
    price: 'Dès 10€',
    oldPrice: null,
    badge: 'promo',
    ctaLabel: 'Voir le masque',
    img: '/assets/masque-mouches.jpg',
    disciplines: ['loisir', 'cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    // liens affiliés Emouchine + Leovet à renseigner (CTA -> href="#" en attendant)
    id: 'anti-mouches-duo',
    name: 'Dites adieu aux mouches',
    category: 'protections',
    tag: 'Anti-mouches',
    detailUrl: '/equipement/protection/spray-anti-mouches/',
    subtitle: 'Nos deux références testées et approuvées',
    desc: "Pour les journées de concours et d'effort intense : l'Emouchine X-Pro, jusqu'à 10h d'efficacité même sous la transpiration. Pour une utilisation quotidienne sans agresser la peau : le Leovet Tam Tam et sa technologie microencapsulée longue durée. Deux produits, deux situations, zéro compromis.",
    price: 'Dès 15€',
    oldPrice: null,
    badge: 'selection',
    ctaLabel: 'Voir le spray',
    img: '/assets/spray-mouches.jpg',
    disciplines: ['loisir', 'cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'guetres-lemieux',
    name: 'Le style et la protection au quotidien',
    category: 'protections',
    tag: 'Protections & tendons',
    equipementUrl: '/equipement/protection/guetres-lemieux/',
    subtitle: 'Le Mieux — guêtres légères, colorées et efficaces',
    desc: "Mesh 3D ultra respirant et coque de protection anatomique dans plus de 20 coloris. Légères, efficaces et parfaites pour l'entraînement quotidien.",
    price: 'Dès 45€',
    oldPrice: null,
    badge: null,
    img: '/assets/guetres-lemieux.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'proteges-boulets-kentucky',
    name: 'La protection boulet de référence',
    category: 'protections',
    tag: 'Protections & boulets',
    equipementUrl: '/equipement/protection/proteges-boulets-kentucky/',
    subtitle: 'Kentucky Horsewear — protège-boulets Young Jump',
    desc: "Mousse à mémoire de forme et doublure en laine mérinos naturelle pour une régulation thermique optimale. Coque renforcée sur les zones d'impact pour les réceptions de saut.",
    price: 'Dès 49€',
    oldPrice: null,
    badge: null,
    img: '/assets/proteges-boulets-kentucky.jpg',
    disciplines: ['cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'guetres-repos-kentucky',
    name: 'Le must-have du box et du transport',
    category: 'protections',
    tag: 'Protections & tendons',
    equipementUrl: '/equipement/protection/guetres-repos-kentucky/',
    subtitle: 'Kentucky Horsewear — guêtres de repos et transport',
    desc: "Polaire polypropylène haute densité et velcro anti-rotation pour un maintien des tendons du genou au boulet. Indispensables pour le box, le transport et la récupération.",
    price: 'Dès 79€ le jeu de 4',
    oldPrice: null,
    badge: null,
    img: '/assets/guetres-repos-kentucky.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'acavallo-gel-pad',
    name: 'Le secret des dos difficiles',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    pepiteUrl: '/pepites/acavallo-gel-pad/',
    subtitle: 'Acavallo Gel Pad — surélevé à l\'arrière, noir',
    desc: "Gel thérapeutique anatomique qui relève la selle à l'arrière pour rééquilibrer l'assiette et soulager le dos du cheval. Profil bas de 8mm, compatible avec toutes les selles.",
    price: '66,60€',
    oldPrice: null,
    badge: 'promo',
    img: '/assets/acavallo-gel-pad.jpg',
    disciplines: ['loisir', 'dressage', 'cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'couvre-reins-polaire',
    name: 'Couvre-reins polaire hiver',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    detailUrl: '/bons-plans/couvre-reins-polaire/',
    desc: "Garde les lombaires au chaud pendant l'échauffement, séchage rapide.",
    price: '42€',
    oldPrice: '55€',
    badge: 'promo',
    img: img('tapis2'),
    disciplines: ['loisir', 'dressage', 'cso'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'tapis-harcour-chic',
    name: 'Le tapis chic de la cavalière française',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    equipementUrl: '/equipement/tapis/harcour-chic/',
    subtitle: 'Harcour — élégance technique, collections exclusives',
    desc: "Marque française fournisseur officiel des équipes de France, coupe anatomique largement dégarrottée et intérieur en coton gaufré 100%. Élégance et technicité pour toutes disciplines.",
    price: '69,98€',
    oldPrice: null,
    badge: null,
    img: '/assets/tapis-harcour-chic.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'tapis-horze-bon-plan',
    name: 'Le bon plan tapis pour toutes les bourses',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    equipementUrl: '/equipement/tapis/horze-bon-plan/',
    subtitle: 'Horze — large choix, prix accessibles, qualité au rendez-vous',
    desc: "Le plus grand choix de tapis en ligne à prix très compétitifs. Qualité constante et fiable, régulièrement en promotion, idéal pour l'entraînement quotidien.",
    price: 'Dès 29€',
    oldPrice: null,
    badge: 'promo',
    img: '/assets/tapis-horze-bon-plan.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'tapis-kentucky',
    name: 'Le tapis premium qui ne démode jamais',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    equipementUrl: '/equipement/tapis/kentucky/',
    subtitle: 'Kentucky Horsewear — matchy matchy, matériaux vegan et qualité haut de gamme',
    desc: "Marque neutre en CO2, matières 100% vegan et gamme matchy matchy incomparable. Le tapis Velvet, effet velours ultra doux, est le plus vendu de la gamme.",
    price: '124,99€',
    oldPrice: null,
    badge: 'premium',
    img: '/assets/tapis-kentucky.jpg',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'tapis-gem',
    name: 'Le tapis technique made in France',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    equipementUrl: '/equipement/tapis/gem-equitation/',
    subtitle: 'GEM Équitation — mesh respirant, personnalisable, sponsor équipe de France',
    desc: "Marque française indépendante, sponsor de l'équipe de France poneys. Mesh 3D ultra-respirant et tapis volontairement fin pour une proximité maximale avec le cheval.",
    price: 'Dès 99€',
    oldPrice: null,
    badge: 'made-in-france',
    img: '/assets/tapis-gem.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'amortisseur-pravins',
    name: "L'amortisseur recommandé par les vétérinaires",
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    equipementUrl: '/equipement/tapis/amortisseur-pravins/',
    subtitle: 'Pravins Sellier — feutre 100% laine, développé avec des saddle fitters',
    desc: "Feutre 100% laine naturelle qui se moule progressivement au dos du cheval. Système de cales interchangeables pour compenser les défauts d'une selle mal adaptée.",
    price: 'Dès 155€',
    oldPrice: null,
    badge: null,
    img: '/assets/amortisseur-pravins.jpg',
    disciplines: ['cso', 'dressage'],
    morphology: ['garrot-saillant', 'dos-creux'],
    budget: '<500',
  },
  {
    id: 'amortisseur-acavallo',
    name: 'La solution gel pour tous les dos',
    category: 'tapis',
    tag: 'Tapis & Amortisseurs',
    equipementUrl: '/equipement/tapis/amortisseur-acavallo/',
    subtitle: 'Acavallo — gel thérapeutique, mémoire de forme, technologie italienne',
    desc: "Technologie gel brevetée hypoallergénique, surface antidérapante et version dégarrottée à cellules hexagonales. La référence italienne des amortisseurs.",
    price: 'Dès 59€',
    oldPrice: null,
    badge: null,
    img: '/assets/acavallo-gel-pad.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: ['garrot-saillant'],
    budget: '<500',
  },
  {
    id: 'airbag-twistair-2',
    name: "L'airbag qui pourrait vous sauver la vie",
    category: 'vetements',
    subcategory: 'airbag',
    tag: 'Airbag',
    pepiteUrl: '/pepites/airbag-twistair-2/',
    equipementUrl: '/equipement/vetements-cavalier/airbag-twistair-2/',
    subtitle: "Horse Pilot Twist'Air 2.0 — connexion aimantée, norme NF, made in France",
    desc: "Fabriqué en France et homologué norme NF S72-800:2022. Système de connexion aimanté à une main, cartouche de 42g, design ultra discret compatible vestes Horse Pilot, certifié EPI avec garantie 2 ans extensible à 3 ans.",
    price: 'À partir de 449€',
    oldPrice: null,
    badge: null,
    img: '/assets/airbag-twistair-2.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'airbag-hitair-complet3',
    name: "Le pionnier japonais de l'airbag équestre",
    category: 'vetements',
    subcategory: 'airbag',
    tag: 'Airbag',
    equipementUrl: '/equipement/vetements-cavalier/airbag-hitair-complet3/',
    subtitle: 'Hit Air Complet 3 — protection intégrale colonne, thorax et cervicales',
    desc: "Marque japonaise pionnière avec plus de 25 ans d'expertise. Couvre l'ensemble de la colonne vertébrale des cervicales au sacrum, plus le thorax, l'abdomen et les côtes flottantes. Homologué FFE et FEI.",
    price: '529€',
    oldPrice: null,
    badge: null,
    img: '/assets/airbag-hitair-complet3.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'airbag-freejump',
    name: 'Le premier airbag homologué norme française NF',
    category: 'vetements',
    subcategory: 'airbag',
    tag: 'Airbag',
    equipementUrl: '/equipement/vetements-cavalier/airbag-freejump/',
    subtitle: 'Freejump — 98ms de gonflage, norme NF S72-800-2022, tissu italien',
    desc: "Premier gilet airbag équitation homologué selon la norme NF S72-800-2022. Gonflage intégral en 98ms, minerve stabilisante intégrée, compatible avec de nombreuses vestes de marques tierces certifiées NF.",
    price: 'À partir de 449€',
    oldPrice: null,
    badge: null,
    img: '/assets/airbag-freejump.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'airbag-helite-zipin2',
    name: "L'airbag français invisible sous la veste",
    category: 'vetements',
    subcategory: 'airbag',
    tag: 'Airbag',
    equipementUrl: '/equipement/vetements-cavalier/airbag-helite-zipin2/',
    subtitle: "Helite Zip'In 2 — 2 en 1, seul ou intégré, premier fabricant européen",
    desc: "Helite, entreprise française fondée en 2002, premier fabricant européen d'airbags. Modèle 2 en 1 : se porte seul ou invisible sous une veste compatible. Gonflage ultra-rapide en 100ms, réarmement mécanique autonome.",
    price: 'Dès 349€',
    oldPrice: null,
    badge: 'made-in-france',
    img: '/assets/airbag-helite-zipin2.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'airbag-equitheme-airsafe',
    name: 'La sécurité Freejump au prix Equithème',
    category: 'vetements',
    subcategory: 'airbag',
    tag: 'Airbag',
    equipementUrl: '/equipement/vetements-cavalier/airbag-equitheme-airsafe/',
    subtitle: 'Equithème Airsafe — technologie Freejump, norme NF, prix accessible',
    desc: "Technologie Freejump sous label Equithème — même performance de gonflage en 98ms, même norme NF S72-800-2022, à un prix plus accessible. Cartouches Freejump obligatoires. Disponible adulte et enfant.",
    price: 'Dès 299€',
    oldPrice: null,
    badge: null,
    img: '/assets/airbag-equitheme-airsafe.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'complement-electroliq',
    name: "L'hydratation essentielle après l'effort",
    category: 'complements',
    tag: 'Soins, Santé & Nutrition',
    equipementUrl: '/equipement/complements/electroliq-balance/',
    subtitle: 'Cavalor Electroliq Balance — électrolytes liquides, récupération rapide',
    desc: "Formule liquide isotonique enrichie en fructose et dextrose, aromatisée à la pomme. Tous les électrolytes clés pour une récupération rapide après l'effort.",
    price: 'Dès 18€ le bidon d\'1L (20 jours d\'utilisation)',
    oldPrice: null,
    badge: null,
    img: '/assets/complement-electroliq.jpg',
    disciplines: ['cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    // lien affilié Cavalor à renseigner (CTA -> href="#" en attendant)
    id: 'complement-recuperation',
    name: "Le chouchou de l'après-entraînement",
    category: 'complements',
    tag: 'Compléments alimentaires',
    detailUrl: '/equipement/complements/cavalor-mash/',
    equipementUrl: '/equipement/complements/cavalor-mash/',
    subtitle: 'Cavalor Mash & Mix — récupération & réhydratation',
    desc: "Le mash préféré des chevaux de sport. Riche en électrolytes, grains soufflés, graines de lin et légumes séchés. Facile à digérer, idéal après la compétition ou les froides journées d'hiver. Il suffit de diluer avec de l'eau chaude.",
    price: 'Dès 6,99€',
    oldPrice: null,
    badge: 'coup-de-coeur',
    ctaLabel: 'Voir le produit',
    img: '/assets/cavalor-mash.jpg',
    disciplines: ['cso', 'dressage', 'endurance', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'complement-mash-reverdy',
    name: 'Le mash français sans mélasse',
    category: 'complements',
    tag: 'Soins, Santé & Nutrition',
    equipementUrl: '/equipement/complements/mash-reverdy/',
    subtitle: 'Reverdy Mash — récupération énergétique, fabriqué en Normandie',
    desc: "Fabriqué en Normandie, garanti sans mélasse — idéal pour les chevaux sensibles à l'insuline. Hautement digestible, favorise le transit et la réhydratation après l'effort.",
    price: 'À partir de 15€',
    oldPrice: null,
    badge: 'made-in-france',
    img: '/assets/mash-reverdy.jpg',
    disciplines: ['cso', 'dressage', 'endurance', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'demelant-duo',
    name: 'Le démêlant lustrant indispensable',
    category: 'complements',
    tag: 'Soins, Santé & Nutrition',
    equipementUrl: '/equipement/complements/demelant-duo/',
    subtitle: 'Ravène Easy Shine — brillance immédiate, crinière impeccable',
    desc: "Le démêlant le plus vendu en France : démêle et lustre en une seule application pour une crinière et une queue brillantes immédiatement. Formule légère à prix imbattable.",
    price: 'Dès 8,99€ le flacon de 750ml',
    oldPrice: null,
    badge: null,
    img: '/assets/demelant-duo.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'complement-anti-mouches-redirect',
    name: 'Dites adieu aux mouches',
    category: 'complements',
    tag: 'Soins, Santé & Nutrition',
    equipementUrl: '/equipement/protection/spray-anti-mouches/',
    subtitle: 'Emouchine X-Pro & Leovet Tam Tam — nos deux références spray',
    desc: "Jusqu'à 10h d'efficacité pour le concours, longue durée au quotidien — on a sélectionné les deux meilleurs sprays du marché pour chaque situation.",
    price: 'Dès 15€',
    oldPrice: null,
    badge: 'ete-indispensable',
    ctaLabel: 'Voir nos recommandations',
    img: '/assets/spray-mouches.jpg',
    disciplines: ['loisir', 'cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'complement-masque-anti-mouches-redirect',
    name: 'Le bon plan masque anti-mouches',
    category: 'complements',
    tag: 'Soins, Santé & Nutrition',
    equipementUrl: '/equipement/protection/masque-anti-mouches/',
    subtitle: 'Fouganza 500 Decathlon — protection complète, prix imbattable',
    desc: "Grille semi-rigide, mesh respirant, compatible chemise anti-mouches — le meilleur rapport qualité/prix du marché pour protéger votre cheval tout l'été.",
    price: 'Dès 10€',
    oldPrice: null,
    badge: 'promo',
    ctaLabel: 'Voir le masque',
    img: '/assets/masque-mouches.jpg',
    disciplines: ['loisir', 'cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    // liens affiliés Kask à renseigner (CTA -> href="#" en attendant)
    id: 'casque-vg1',
    name: "Le casque qui fait l'unanimité",
    category: 'vetements',
    subcategory: 'casques',
    tag: 'Casques',
    detailUrl: '/equipement/vetements-cavalier/casque-kask/',
    equipementUrl: '/equipement/vetements-cavalier/casque-kask/',
    subtitle: 'Kask Star Lady Pure Shine — la référence italienne du haut niveau',
    desc: "Plébiscité par les plus grandes cavalières, le Kask Star Lady Pure Shine allie sécurité certifiée CE VG1, légèreté et élégance italienne. Fabriqué 100% en Italie, avec son système Fit System breveté et sa mousse en laine mérinos, c'est le best-seller ultra confortable qui ne fait aucun compromis.",
    price: 'Dès 500€',
    oldPrice: null,
    badge: 'premium',
    ctaLabel: 'Voir le casque',
    img: '/assets/casque-kask-star-lady.jpg',
    disciplines: ['cso', 'dressage', 'loisir', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'casque-samshield',
    name: "L'icône absolue du casque de concours",
    category: 'vetements',
    subcategory: 'casques',
    tag: 'Casques',
    equipementUrl: '/equipement/vetements-cavalier/casque-samshield/',
    subtitle: 'Samshield — sécurité française, design personnalisable à l\'infini',
    desc: "Coque multi-densité polystyrène et polycarbonate, jugulaire semi-rigide anti-mouvement et personnalisation infinie. Utilisé par les meilleurs cavaliers mondiaux.",
    price: 'à partir de 450€',
    oldPrice: null,
    badge: null,
    img: '/assets/casque-samshield.jpg',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '500-1500',
  },
  {
    id: 'casque-naca',
    name: "Le casque français qui vient de l'aéronautique",
    category: 'vetements',
    subcategory: 'casques',
    tag: 'Casques',
    equipementUrl: '/equipement/vetements-cavalier/casque-naca/',
    subtitle: 'NACA Gravity — carbone, visière magnétique, fabriqué à Signes (Var)',
    desc: "Visière magnétique amovible révolutionnaire, jugulaire XP en fibre de carbone brevetée. Fabrication 100% française à partir de matériaux composites aéronautiques.",
    price: 'à partir de 373€ (coque + mousse + visière)',
    oldPrice: null,
    badge: 'made-in-france',
    img: '/assets/casque-naca.jpg',
    disciplines: ['cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '500-1500',
  },
  {
    id: 'casque-equitheme',
    name: 'Le bon plan sécurité pour toutes les bourses',
    category: 'vetements',
    subcategory: 'casques',
    tag: 'Casques',
    equipementUrl: '/equipement/vetements-cavalier/casque-equitheme/',
    subtitle: 'Equithème — qualité française, normes strictes, prix accessibles',
    desc: "Coque ABS ultra-résistante et calotte EPS haute densité, système Adjust-Fit et centaines de points de ventilation. Le meilleur rapport qualité/prix du marché.",
    price: 'à partir de 80€',
    oldPrice: null,
    badge: 'promo',
    img: '/assets/casque-equitheme.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'casque-flexon-armet',
    name: 'Le casque pensé pour ceux qui persévèrent',
    category: 'vetements',
    subcategory: 'casques',
    tag: 'Casques',
    equipementUrl: '/equipement/vetements-cavalier/casque-flexon-armet/',
    subtitle: 'Flex-On Armet — technologie, design contemporain, faible impact carbone',
    desc: "Coque ABS choc teinté, système LAC pour un ajustement nuque précis et visière Zytel qui se déforme sans casser. 119 stickers aimantés pour personnaliser à l'infini.",
    price: 'Dès 350€ (casque + mousse)',
    oldPrice: null,
    badge: null,
    img: '/assets/casque-flexon-armet.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'manteau-horse-pilot',
    name: 'Le manteau qui brave tous les hivers',
    category: 'vetements',
    subcategory: 'tenue-tous-temps',
    tag: 'Manteau',
    equipementUrl: '/equipement/vetements-cavalier/manteau-horse-pilot/',
    subtitle: 'Horse Pilot — doudoune technique à capuche, cavalière & ville',
    desc: "Coupe spécifique équitation allongée à l'arrière, matières techniques respirantes et garnissage doudoune chaud sans alourdir. Aussi à l'aise à l'écurie qu'en ville.",
    price: 'Dès 200€',
    oldPrice: null,
    badge: null,
    img: '/assets/manteau-horse-pilot.jpg',
    imgPosition: 'top',
    disciplines: ['loisir', 'cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'veste-harcour-simhat',
    name: "La veste mi-saison qu'on ne quitte plus",
    category: 'vetements',
    subcategory: 'tenue-tous-temps',
    tag: 'Veste',
    equipementUrl: '/equipement/vetements-cavalier/veste-harcour-simhat/',
    subtitle: 'Harcour Simhat — softshell élégant, chaud sans alourdir',
    desc: "Design épuré et cintré, manches taillées pour le confort en selle et matière softshell déperlante coupe-vent. Élégante à cheval comme en ville.",
    price: 'Dès 119€',
    oldPrice: null,
    badge: null,
    img: '/assets/veste-harcour-simhat.jpg',
    imgPosition: 'top',
    disciplines: ['loisir', 'cso', 'dressage'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'kway-qhp',
    name: 'Le must-have pour les jours de pluie',
    category: 'vetements',
    subcategory: 'tenue-tous-temps',
    tag: 'Imperméable',
    equipementUrl: '/equipement/vetements-cavalier/kway-qhp/',
    subtitle: 'QHP — k-way transparent, léger, protège la tenue de concours',
    desc: "Imperméable transparent ultra léger et compact qui protège la veste de concours sans la cacher. L'accessoire indispensable du sac de concours.",
    price: 'Dès 20€',
    oldPrice: null,
    badge: null,
    img: '/assets/kway-qhp.jpg',
    imgPosition: 'top',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'manteau-mountain-horse',
    name: 'Le manteau d\'hiver qui brave tous les temps',
    category: 'vetements',
    subcategory: 'tenue-tous-temps',
    tag: 'Manteau',
    equipementUrl: '/equipement/vetements-cavalier/manteau-mountain-horse/',
    subtitle: 'Horze — manteau long imperméable, chaud et technique',
    desc: "Coupe longue descendant aux cuisses, rembourrage chaud sans alourdir et matière imperméable coupe-vent. Capuche intégrée ajustable, coloris Dark Navy sobre et élégant.",
    price: 'Dès 89,99€',
    oldPrice: null,
    badge: null,
    img: '/assets/manteau-horze-hiver.png',
    disciplines: ['loisir', 'endurance', 'cso', 'dressage'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'veste-harcour-kanji-hitair',
    name: "La veste de concours avec airbag intégré",
    category: 'vetements',
    subcategory: 'veste-concours',
    tag: 'Veste de concours',
    equipementUrl: '/equipement/vetements-cavalier/veste-harcour-kanji-hitair/',
    subtitle: 'Harcour Kanji x Hit Air — élégance et protection maximale',
    desc: "Première veste de concours française avec doublure airbag Ouraye intégrée invisible. Coupe cintrée, matière stretch et fixation rapide par boutons pression.",
    price: '219,98€ (veste seule) — 619,98€ (pack veste + airbag)',
    oldPrice: null,
    badge: null,
    img: '/assets/veste-harcour-kanji.jpg',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '500-1500',
  },
  {
    id: 'veste-harcour-hotaka-hitair',
    name: "La veste de concours Harcour sans compromis",
    category: 'vetements',
    subcategory: 'veste-concours',
    tag: 'Veste de concours',
    equipementUrl: '/equipement/vetements-cavalier/veste-harcour-hotaka-hitair/',
    subtitle: 'Harcour Topaz — élégance française, coupe cintrée, toutes disciplines',
    desc: "Coupe cintrée et ajustée, tissu stretch bi-composant respirant, empiècements mesh extensibles dans le dos et sous les bras. Une veste de concours classique sans compatibilité airbag, fournisseur officiel des équipes de France.",
    price: 'Dès 159,98€',
    oldPrice: null,
    badge: null,
    img: '/assets/veste-harcour-topaz.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'veste-equitheme-comptair',
    name: 'La veste technique pour débuter en sécurité',
    category: 'vetements',
    subcategory: 'veste-concours',
    tag: 'Veste de concours',
    equipementUrl: '/equipement/vetements-cavalier/veste-equitheme-comptair/',
    subtitle: 'Equithème Comptair — élégante, légère, compatible Zipair Helite',
    desc: "Compatible avec le gilet airbag PRO SERIES Zipair de Helite. Tissu élasthanne stretch, légère et souple, prix plus accessible que les vestes airbag intégrées.",
    price: 'Dès 150€',
    oldPrice: null,
    badge: null,
    img: '/assets/veste-equitheme-comptair.jpg',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'veste-privilege-airsafe',
    name: "L'élégance française pour les concours en extérieur",
    category: 'vetements',
    subcategory: 'veste-concours',
    tag: 'Veste de concours',
    equipementUrl: '/equipement/vetements-cavalier/veste-privilege-airsafe/',
    subtitle: 'Privilège Équitation Airsafe — chic, technique et sécurisée',
    desc: "Compatible avec les principaux systèmes airbag du marché, tissu microperforé UPF50+ et coupe cintrée avec finitions soignées. La référence française du concours.",
    price: '179€',
    oldPrice: null,
    badge: null,
    img: '/assets/veste-privilege-airsafe.jpg',
    disciplines: ['cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
  {
    // liens affiliés Horse Pilot à renseigner (CTA -> href="#" en attendant) — conservé pour le pick homepage (featuredIds), retiré de la grille Équipement > Pantalon
    id: 'jodhpur-silicone-genoux',
    name: 'Le pantalon qui change tout',
    category: 'vetements',
    subcategory: 'pantalon',
    tag: 'Pantalon',
    detailUrl: '/equipement/vetements-cavalier/pantalon-horse-pilot/',
    equipementUrl: '/equipement/vetements-cavalier/pantalon-horse-pilot/',
    subtitle: 'Horse Pilot — technicité française, confort de seconde peau',
    desc: "La marque française qui a révolutionné le pantalon d'équitation. Tissu bi-stretch, coutures plates anti-frottements, grips genoux, technologie UV Block et compression pour la récupération. Le X-Design est l'iconique pour la compétition, le X-Balance 2.0 le plus léger pour l'entraînement. À acheter en soldes ou d'occasion pour optimiser le budget.",
    price: 'Dès 180€',
    oldPrice: null,
    badge: 'made-in-france',
    ctaLabel: 'Voir le pantalon',
    img: '/assets/pantalon-horsepilot-xdesign.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'pantalon-pomme-equestrian',
    name: "Le pantalon qui entre l'équitation dans le 21ème siècle",
    category: 'vetements',
    subcategory: 'pantalon',
    tag: 'Pantalon',
    equipementUrl: '/equipement/vetements-cavalier/pantalon-pomme-equestrian/',
    subtitle: 'Pomme Equestrian — leggings et pantalons techniques ultra modernes',
    desc: "Marque fondée par des cavalières pour des cavalières, coupe et style ultra contemporains. Tissu stretch 4 directions, grip silicone full seat ou genoux selon les modèles, grandes poches pratiques.",
    price: 'Dès 120€',
    oldPrice: null,
    badge: null,
    img: '/assets/pantalon-pomme-equestrian.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'pantalon-harcour-jaltika',
    name: "Le best-seller français de l'entraînement",
    category: 'vetements',
    subcategory: 'pantalon',
    tag: 'Pantalon',
    equipementUrl: '/equipement/vetements-cavalier/pantalon-harcour-jaltika/',
    subtitle: 'Harcour Jaltika — Rider Stretch, grip genoux, coordinable à l\'infini',
    desc: "Fournisseur officiel des équipes de France d'équitation depuis 2017. Matière Rider Stretch exclusive, grip silicone aux genoux, version full grip disponible, coloris coordonnés à toute la gamme Harcour.",
    price: 'Dès 89,99€',
    oldPrice: null,
    badge: 'made-in-france',
    img: '/assets/pantalon-harcour-jaltika.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'pantalon-equitheme-claudine',
    name: 'Le bon plan concours à petit prix',
    category: 'vetements',
    subcategory: 'pantalon',
    tag: 'Pantalon',
    equipementUrl: '/equipement/vetements-cavalier/pantalon-equitheme-claudine/',
    subtitle: 'Equithème Claudine — fond silicone, taille haute, stretch total',
    desc: "Meilleur rapport qualité/prix du marché. Fond silicone antidérapant full seat, ceinture haute avec rehausse arrière, bas de jambe en élasthanne ajouré, deux grandes poches profondes.",
    price: 'Dès 37,49€ (en promo) — 49,99€ plein tarif',
    oldPrice: '49,99€',
    badge: 'promo',
    img: '/assets/pantalon-equitheme-claudine.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'pantalon-horze-mira-grandprix',
    name: 'Le large choix à prix accessible',
    category: 'vetements',
    subcategory: 'pantalon',
    tag: 'Pantalon',
    equipementUrl: '/equipement/vetements-cavalier/pantalon-horze-mira-grand-prix/',
    pepiteUrl: '/equipement/vetements-cavalier/pantalon-horze-mira-grand-prix/',
    subtitle: 'Horze — deux modèles phares pour tous les usages',
    desc: "Deux modèles complémentaires pour couvrir tous les besoins à prix raisonnable. Mira : fond intégral grip toutes saisons. Grand Prix : legging fond grip silicone intégral avec poches téléphone cuisse.",
    price: 'Dès 51,99€ (Mira en promo) — Grand Prix dès 69,99€',
    oldPrice: null,
    badge: 'promo',
    img: '/assets/pantalon-horze-mira-grandprix.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'pantalon-kramer',
    name: 'Le plus grand choix en un seul endroit',
    category: 'vetements',
    subcategory: 'pantalon',
    tag: 'Pantalon',
    equipementUrl: '/equipement/vetements-cavalier/pantalon-kramer/',
    subtitle: 'Kramer — des centaines de pantalons, toutes marques, tous budgets',
    desc: "Plus grand catalogue de pantalons d'équitation en ligne. Du basique à moins de 30€ au pantalon premium haut de gamme, toutes les grandes marques réunies au même endroit : Pikeur, Equiline, ELT, Pénélope, Cavallo, Schockemöhle...",
    price: 'Dès 29€',
    oldPrice: null,
    badge: 'tous-budgets',
    img: '/assets/pantalon-kramer.jpg',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'bottes-ego7-aries-orion',
    name: "L'élégance italienne accessible",
    category: 'vetements',
    subcategory: 'bottes',
    tag: 'Bottes',
    equipementUrl: '/equipement/vetements-cavalier/bottes-ego7-aries-orion/',
    subtitle: 'Ego 7 — design italien, cuir pleine fleur, deux modèles iconiques',
    desc: "Marque italienne spécialisée dans l'équipement équestre. Aries sans lacets pour le dressage, Orion avec lacets et panneau extensible pour le CSO. Demi-mesure et embauchoirs gonflables inclus.",
    price: 'Dès 349€',
    oldPrice: null,
    badge: null,
    img: '/assets/bottes-ego7.jpg',
    imgPosition: 'top',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'bottes-sergio-grasso',
    name: "L'artisanat italien à son sommet",
    category: 'vetements',
    subcategory: 'bottes',
    tag: 'Bottes',
    equipementUrl: '/equipement/vetements-cavalier/bottes-sergio-grasso/',
    subtitle: 'Sergio Grasso — technologie ProComf®, cuir Nappa, semelle Vibram',
    desc: "Marque italienne entièrement dédiée aux bottes d'équitation. Technologie ProComf.Evo® exclusive, cuir Nappa ultra confortable, panneau SG Ultratech breveté. Modèles Evolution et Revolution.",
    price: 'À partir de 300€',
    oldPrice: null,
    badge: 'premium',
    img: '/assets/bottes-sergio-grasso.jpg',
    imgPosition: 'top',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '500-1500',
  },
  {
    id: 'bottes-parlanti',
    name: 'Le luxe équestre fait à la main',
    category: 'vetements',
    subcategory: 'bottes',
    tag: 'Bottes',
    equipementUrl: '/equipement/vetements-cavalier/bottes-parlanti/',
    subtitle: 'Parlanti — bottes sur mesure, cuir premium, icône du grand sport',
    desc: "Marque italienne fondée en 1988, référence absolue du haut de gamme. Fabrication entièrement artisanale, cousue et assemblée à la main en Italie. Option sur mesure disponible.",
    price: 'à partir de 500€',
    oldPrice: null,
    badge: 'premium',
    img: '/assets/bottes-parlanti.jpg',
    imgPosition: 'top',
    disciplines: ['cso', 'dressage'],
    morphology: [],
    budget: '500-1500',
  },
  {
    id: 'bottes-horze',
    name: 'La botte de qualité sans se ruiner',
    category: 'vetements',
    subcategory: 'bottes',
    tag: 'Bottes',
    equipementUrl: '/equipement/vetements-cavalier/bottes-horze/',
    subtitle: 'Horze — cuir ou synthétique, demi-mesure, large choix de morphologies',
    desc: "Large gamme de bottes pour tous les budgets et toutes les morphologies. Modèles demi-mesure disponibles, cuir souple dès le premier jour sur les modèles premium.",
    price: 'à partir de 99€',
    oldPrice: null,
    badge: null,
    img: '/assets/bottes-horze.jpg',
    imgFit: 'contain',
    imgBg: '#FDF8F2',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'bottes-kramer',
    name: 'Le plus grand choix de bottes en un seul endroit',
    category: 'vetements',
    subcategory: 'bottes',
    tag: 'Bottes',
    equipementUrl: '/equipement/vetements-cavalier/bottes-kramer/',
    subtitle: 'Kramer — toutes marques, tous budgets, Pikeur, Cavallo, Schockemöhle',
    desc: "Plus grand catalogue de bottes d'équitation en ligne. Marques allemandes exclusives : Pikeur, Schockemöhle, Cavallo, Covalliero. Du synthétique basique à la botte sur mesure.",
    price: 'à partir de 80€',
    oldPrice: null,
    badge: 'tous-budgets',
    img: '/assets/bottes-kramer.jpg',
    imgFit: 'contain',
    imgBg: '#FDF8F2',
    disciplines: ['cso', 'dressage', 'loisir'],
    morphology: [],
    budget: '<500',
  },
  {
    id: 'gants-hiver-tactile',
    name: 'Gants hiver compatibles écran tactile',
    category: 'vetements',
    detailUrl: '/bons-plans/gants-hiver-tactile/',
    desc: "Doublure thermique et paume renforcée, sans perdre le contact avec les rênes.",
    price: '29€',
    oldPrice: '38€',
    badge: 'promo',
    img: img('gants1'),
    disciplines: ['loisir', 'cso', 'dressage', 'endurance'],
    morphology: [],
    budget: '<500',
  },
];

const CF_OOPS = [
  {
    id: 'selle-bas-prix-generique',
    title: 'Les selles "universelles" premier prix en synthétique bas de gamme',
    category: 'Selles',
    severity: 'fuir',
    piege: "Un arçon générique qui ne suit aucune morphologie précise : garanti de blesser le dos de ton cheval à moyen terme, même si le prix fait rêver au début.",
    conseil: "Vise au minimum une selle avec un choix d'arçon (étroit / medium / large).",
  },
  {
    id: 'tapis-trop-fin',
    title: 'Les tapis "déco" ultra fins sans réel matelassage',
    category: 'Tapis',
    severity: 'attention',
    piege: "Jolis en photo, mais quasiment plats une fois lavés : ils n'amortissent plus rien après quelques utilisations.",
    conseil: "Cherche un grammage annoncé (mousse ou molleton épais) et prévois toujours un tapis de rechange pour l'entraînement quotidien.",
  },
  {
    id: 'complements-miracle',
    title: 'Les compléments \"miracle\" sans liste d\'ingrédients claire',
    category: 'Compléments',
    severity: 'fuir',
    piege: "Packaging qui promet monts et merveilles, mais étiquette illisible ou dosages actifs ridicules noyés dans des additifs.",
    conseil: "Privilégie les marques qui affichent clairement les dosages en grammes par dose et qui sont conformes aux règlements anti-dopage FFE/FEI.",
  },
  {
    id: 'casque-sans-norme',
    title: 'Les casques \"fashion\" sans norme de sécurité à jour',
    category: 'Casques',
    severity: 'fuir',
    piege: "Certains casques d'importation affichent un look sympa mais aucune norme VG1 ou équivalente clairement certifiée.",
    conseil: "Ne transige jamais là-dessus : vérifie la norme sur l'étiquette intérieure, pas seulement sur la fiche produit en ligne.",
  },
  {
    id: 'jodhpur-grip-qui-glisse',
    title: 'Les pantalons \"grip\" dont le silicone s\'effrite après 3 lavages',
    category: 'Vêtements',
    severity: 'attention',
    piege: "Le grip promis en photo devient une surface lisse (voire collante et sale) après quelques passages en machine.",
    conseil: "Regarde les avis clients sur la tenue dans le temps, pas juste la description produit, et lave à l'envers en cycle délicat. Les pantalons que nous te recommandons sur le site répondent à ce problème !",
  },
  {
    id: 'protections-boulets-rigides',
    title: 'Les protège-boulets trop rigides bas de gamme',
    category: 'Protections',
    severity: 'attention',
    piege: "Une coque dure mal ajustée peut créer des points de frottement et blesser plus qu'elle ne protège.",
    conseil: "Préfère un modèle avec mousse intérieure ajustable et essaie toujours la fermeture en mouvement avant de valider la taille.",
  },
];

window.CF_DATA = { products: CF_PRODUCTS, oops: CF_OOPS };
